language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  app:
    master: nhsdashboard-staging
    production: nhsdashboard
  api_key:
    secure: RJbqi6AF/ZiwmvGJUjhj/mgmTU5seU2GUdiwRoSXb8zsnok4y0xpEMYqVPgZ60bsj9VcqNe3SNW9ilq+ZA/RLkzjaY/kakO5iSckAp7rbsaZ9t8UFpwsQMSROmmIZcsFUQzT6qSQgcCT6CXUDZbTtXZtizGbK/Zf+7sfQStcYxF1I2t3YQj94spqMLpsr8JwmLRLQShmOYLvPo7HK1OR9OvI3T7sHQ9zAayJAkFn98kvGmnMWwQAuJFuSS8czZOoz90hSdlYCi7jFN/XABhD4OkvQN6EbD5Tj2jyL0c6lTcpszquQcY8n647UmTW8yCHRm+Hrzge6uRYZRG28hXhEsDr3tl4HnXLPu610RcuE9SP0dfgy1Em9UedV/q95O6ZSYRbQT9tIItxclkLJwwS/90EaO9ZsELYFl452B0B2e+uZ+lholtAKW3yM9TwPNNeD1/+V/NVKp8zKdC/0zHf3h2Zdl5g7g/hlHvIIjWtmFpDgfExJE3afSXcemlDbgff2aZDROesko3SNZEfH+9oOjgD6djLPsprUATDE8fAnbCImtLJspSOtg3wpBh2vsluNphEHb1GUh0pLrnJ0yfPr3dHCk+1/V1fZFIycjSUS9thZARSs+VIywlYe0+Ed1qHGdJVN6WR5KvmwC2iFF/wSuIg9/UDNPBXo2ZdL1i0XFI=
script:
  - npm run lint
notifications:
  slack:
    secure: D4CMIxy5YgETLZwdpH0e/fOaxMMXtk5tKfYGyH49fSoYzncKdH98wD0cptoG3pMop/6UQ/E4sis1/C81pPBRvav4PVARNXZT/ikLGE8paTHhRjlfPHgAf2Xt9Wj18j4pEi/yoGXKdffUbNQiEoNIS2F31UutmDsFhKG0vlBSMNub6neeQKYCnxRkFlxrMCjE0RhTtakBhgzkY2gbpVYNlja72Tm5mMGblzYHSCR7IpyzOGdmYDO5dSidzmnWcfe6AVSyT8s/EtZ14tOxfBqi5Fsls4Rbk7ygKXIDC+qYgxCzRBVAoaYgpP37JsRHAEjr5CrQMxuJpA1AFTgsGHeAG/BZIFVZFCoH6IYvI2pUQTXfFhOsE2w2pyq9ZlLaBgXhbwA1unD0o0T9GwVVHmTqnLKqZK+AevfllPFNCz0h7/i/d43IC4Rtsl0fsS2gTnzVtrOZVumUl1P4DV7MTA9U4UqADi+i4UA8L2VeNIwdE/Unh5K4kyBr54jdDjOZmWJZLCNZ9Sbh/T1Bpjd9Hw3JO086WWAPc+awKdh7d4/Zlf0wz6mOD4B71acnRpNwJja2L7a6nyo1FxXyVmXmZR3H5A5y3nupj5UTFYo5dJmp0RJK6oSTbL1cqXR6v5kEbud4X/L6WbXx5N3jpHgKL1UwVvJJpzsYh7km9v5zVaoD6gs=

